In [1]:
import pandas as pd

In [3]:
from pathlib import Path
root_path  = Path.cwd().parent
print(root_path)
# df = pd.read_csv(data_path / 'data.csv')

/home/gnart/gblabs/stables

In [5]:
df = pd.read_csv(root_path / 'data/processed/chain_data_2025-03-30.csv')
df.head()

,id,name,symbol,chain,current,prevDay,prevWeek,prevMonth
0,1,Tether,USDT,Optimism,3.967111e+08,3.967059e+08,3.925205e+08,3.643182e+08
1,1,Tether,USDT,Statemine,2.399930e+05,2.399930e+05,2.399930e+05,2.399930e+05
2,1,Tether,USDT,Manta,6.185203e+06,6.185203e+06,6.181323e+06,7.966532e+06
3,1,Tether,USDT,Harmony,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,1,Tether,USDT,ThunderCore,6.215052e+05,6.215052e+05,6.186862e+05,7.075505e+05

# per chain

In [14]:
df_chain = df.groupby('chain').agg({'current': 'sum', 'prevDay': 'sum'}).reset_index()
df_chain['change_day'] = df_chain['current'] - df_chain['prevDay']
df_chain['change_day_pct'] = (df_chain['change_day'] / df_chain['prevDay'])*100

df_chain.sort_values('change_day_pct', ascending=False)

             chain       current       prevDay    change_day  change_day_pct
17      Bittorrent  4.021950e+05  3.360069e+05  6.618816e+04       19.698456
110          Sonic  4.458730e+08  4.273918e+08  1.848116e+07        4.324172
106          Shape  2.828582e+04  2.768782e+04  5.980000e+02        2.159794
46         Fraxtal  1.150843e+08  1.138458e+08  1.238472e+06        1.087850
12            Base  4.217416e+09  4.173744e+09  4.367231e+07        1.046358
..             ...           ...           ...           ...             ...
32       DefiChain  0.000000e+00  0.000000e+00  0.000000e+00             NaN
51            Heco  0.000000e+00  0.000000e+00  0.000000e+00             NaN
61          Kadena  0.000000e+00  0.000000e+00  0.000000e+00             NaN
90        Ontology  0.000000e+00  0.000000e+00  0.000000e+00             NaN
122  Terra Classic  0.000000e+00  0.000000e+00  0.000000e+00             NaN

[145 rows x 5 columns]

In [20]:
df_id = df.groupby('name').agg({'current': 'sum', 'prevDay': 'sum'}).reset_index()
df_id['change_day'] = df_id['current'] - df_id['prevDay']
df_id['change_day_pct'] = (df_id['change_day'] / df_id['prevDay'])*100
df_id.sort_values('change_day_pct', ascending=False)

df_id.sort_values('change_day_pct', ascending=False)

,name,current,prevDay,change_day,change_day_pct
29,Celo Euro,5.356305e+06,3.692869e+06,1.663436e+06,45.044535
143,Reservoir Stablecoin,4.238070e+07,3.293318e+07,9.447518e+06,28.686930
120,OpenDollar USDO,5.002102e+07,4.655384e+07,3.467186e+06,7.447691
146,Rings scUSD,8.085843e+07,7.647839e+07,4.380039e+06,5.727159
182,USDD,2.410152e+08,2.303461e+08,1.066916e+07,4.631796
...,...,...,...,...,...
109,Move Dollar,3.846074e+06,4.147242e+06,-3.011686e+05,-7.261900
216,Zunami USD,2.267934e+05,2.479341e+05,-2.114071e+04,-8.526745
204,Vai,2.587154e+06,2.932559e+06,-3.454045e+05,-11.778264
54,EUROe Stablecoin,4.322004e+05,6.442324e+05,-2.120320e+05,-32.912346
168,TerraClassicUSD,0.000000e+00,0.000000e+00,0.000000e+00,NaN