## Setup

In [1]:
import polars as pl
import matplotlib.pyplot as plt
import requests

import warnings
warnings.filterwarnings("ignore")
import os
from pathlib import Path
import sys
project_root = Path().resolve().parent

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
    print(f"Added {project_root.stem} to sys.path")

from src.utils.llama import StableLlamaAPI

stable_llama = StableLlamaAPI()

Added stables to sys.path

In [2]:
df_usde = stable_llama.get_a_stablecoin(id=146)

In [10]:
df_chain_balances = pl.DataFrame(df_usde['chainBalances'], strict=False)
df_chain_balances

shape: (1, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Optimism  ┆ Metis     ┆ Scroll    ┆ Kava      ┆ … ┆ Linea     ┆ Solana    ┆ Arbitrum  ┆ Blast    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ struct[1] ┆ struct[1] ┆ struct[1] ┆ struct[1] ┆   ┆ struct[1] ┆ struct[1] ┆ struct[1] ┆ struct[1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ {[{172506 ┆ {[{172506 ┆ {[{172506 ┆ {[{172506 ┆ … ┆ {[{172506 ┆ {[{172506 ┆ {[{172506 ┆ {[{17250 │
│ 2400,{670 ┆ 2400,{117 ┆ 2400,{508 ┆ 2400,{17} ┆   ┆ 2400,{669 ┆ 2400,{647 ┆ 2400,{427 ┆ 62400,{1 │
│ 1},{6701, ┆ 4},{1174, ┆ 3248},{50 ┆ ,{17,{{{1 ┆   ┆ 98},{6699 ┆ 9430},{64 ┆ 89547},{4 ┆ 1165299} │
│ {{{…      ┆ {{{…      ┆ 832…      ┆ 7}}…      ┆   ┆ 8,{…      ┆ 794…      ┆ 278…      ┆ ,{1116…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
# pl.DataFrame(
df_usde['chainBalances']['Optimism']['tokens']
# )

[{'date': 1725062400,
  'circulating': {'peggedUSD': 6701},
  'bridgedTo': {'peggedUSD': 6701,
   'bridges': {'not-found': {'not-found': {'amount': 6701}}}}},
 {'date': 1725148800,
  'circulating': {'peggedUSD': 6701},
  'bridgedTo': {'peggedUSD': 6701,
   'bridges': {'not-found': {'not-found': {'amount': 6701}}}}},
 {'date': 1725235200,
  'circulating': {'peggedUSD': 6701},
  'bridgedTo': {'peggedUSD': 6701,
   'bridges': {'not-found': {'not-found': {'amount': 6701}}}}},
 {'date': 1725321600,
  'circulating': {'peggedUSD': 6756},
  'bridgedTo': {'peggedUSD': 6756,
   'bridges': {'not-found': {'not-found': {'amount': 6756}}}}},
 {'date': 1725408000,
  'circulating': {'peggedUSD': 6708},
  'bridgedTo': {'peggedUSD': 6708,
   'bridges': {'not-found': {'not-found': {'amount': 6708}}}}},
 {'date': 1725494400,
  'circulating': {'peggedUSD': 6708},
  'bridgedTo': {'peggedUSD': 6708,
   'bridges': {'not-found': {'not-found': {'amount': 6708}}}}},
 {'date': 1725580800,
  'circulating': {'peggedUSD': 6708},
  'bridgedTo': {'peggedUSD': 6708,
   'bridges': {'not-found': {'not-found': {'amount': 6708}}}}},
 {'date': 1725667200,
  'circulating': {'peggedUSD': 6708},
  'bridgedTo': {'peggedUSD': 6708,
   'bridges': {'not-found': {'not-found': {'amount': 6708}}}}},
 {'date': 1725753600,
  'circulating': {'peggedUSD': 6708},
  'bridgedTo': {'peggedUSD': 6708,
   'bridges': {'not-found': {'not-found': {'amount': 6708}}}}},
 {'date': 1725840000,
  'circulating': {'peggedUSD': 6703},
  'bridgedTo': {'peggedUSD': 6703,
   'bridges': {'not-found': {'not-found': {'amount': 6703}}}}},
 {'date': 1725926400,
  'circulating': {'peggedUSD': 6703},
  'bridgedTo': {'peggedUSD': 6703,
   'bridges': {'not-found': {'not-found': {'amount': 6703}}}}},
 {'date': 1726012800,
  'circulating': {'peggedUSD': 6697},
  'bridgedTo': {'peggedUSD': 6697,
   'bridges': {'not-found': {'not-found': {'amount': 6697}}}}},
 {'date': 1726099200,
  'circulating': {'peggedUSD': 6686},
  'bridgedTo': {'peggedUSD': 6686,
   'bridges': {'not-found': {'not-found': {'amount': 6686}}}}},
 {'date': 1726185600,
  'circulating': {'peggedUSD': 6703},
  'bridgedTo': {'peggedUSD': 6703,
   'bridges': {'not-found': {'not-found': {'amount': 6703}}}}},
 {'date': 1726272000,
  'circulating': {'peggedUSD': 6710},
  'bridgedTo': {'peggedUSD': 6710,
   'bridges': {'not-found': {'not-found': {'amount': 6710}}}}},
 {'date': 1726358400,
  'circulating': {'peggedUSD': 6703},
  'bridgedTo': {'peggedUSD': 6703,
   'bridges': {'not-found': {'not-found': {'amount': 6703}}}}},
 {'date': 1726444800,
  'circulating': {'peggedUSD': 6781},
  'bridgedTo': {'peggedUSD': 6781,
   'bridges': {'not-found': {'not-found': {'amount': 6781}}}}},
 {'date': 1726531200,
  'circulating': {'peggedUSD': 6781},
  'bridgedTo': {'peggedUSD': 6781,
   'bridges': {'not-found': {'not-found': {'amount': 6781}}}}},
 {'date': 1726617600,
  'circulating': {'peggedUSD': 6700},
  'bridgedTo': {'peggedUSD': 6700,
   'bridges': {'not-found': {'not-found': {'amount': 6700}}}}},
 {'date': 1726704000,
  'circulating': {'peggedUSD': 6700},
  'bridgedTo': {'peggedUSD': 6700,
   'bridges': {'not-found': {'not-found': {'amount': 6700}}}}},
 {'date': 1726790400,
  'circulating': {'peggedUSD': 6715},
  'bridgedTo': {'peggedUSD': 6715,
   'bridges': {'not-found': {'not-found': {'amount': 6715}}}}},
 {'date': 1726876800,
  'circulating': {'peggedUSD': 9244},
  'bridgedTo': {'peggedUSD': 9244,
   'bridges': {'not-found': {'not-found': {'amount': 9244}}}}},
 {'date': 1726963200,
  'circulating': {'peggedUSD': 9255},
  'bridgedTo': {'peggedUSD': 9255,
   'bridges': {'not-found': {'not-found': {'amount': 9255}}}}},
 {'date': 1727049600,
  'circulating': {'peggedUSD': 9220},
  'bridgedTo': {'peggedUSD': 9220,
   'bridges': {'not-found': {'not-found': {'amount': 9220}}}}},
 {'date': 1727136000,
  'circulating': {'peggedUSD': 9213},
  'bridgedTo': {'peggedUSD': 9213,
   'bridges': {'not-found': {'not-found': {'amount': 9213}}}}},
 {'date': 1727222400,
  'circulating': {'peggedUSD': 9210},
  'bridgedTo': {'peggedUSD': 9210,
   'bridges': {'not-found': {'not-found': {'amount': 9210}}}}},
 {'date': 1727308800,
  'circulating': {'peggedUSD': 9263},
  'bridgedTo': {'peggedUSD': 9263,
   'bridges': {'not-found': {'not-found': {'amount': 9263}}}}},
 {'date': 1727395200,
  'circulating': {'peggedUSD': 9313},
  'bridgedTo': {'peggedUSD': 9313,
   'bridges': {'not-found': {'not-found': {'amount': 9313}}}}},
 {'date': 1727481600,
  'circulating': {'peggedUSD': 9300},
  'bridgedTo': {'peggedUSD': 9300,
   'bridges': {'not-found': {'not-found': {'amount': 9300}}}}},
 {'date': 1727568000,
  'circulating': {'peggedUSD': 9309},
  'bridgedTo': {'peggedUSD': 9309,
   'bridges': {'not-found': {'not-found': {'amount': 9309}}}}},
 {'date': 1727654400,
  'circulating': {'peggedUSD': 9296},
  'bridgedTo': {'peggedUSD': 9296,
   'bridges': {'not-found': {'not-found': {'amount': 9296}}}}},
 {'date': 1727740800,
  'circulating': {'peggedUSD': 9296},
  'bridgedTo': {'peggedUSD': 9296,
   'bridges': {'not-found': {'not-found': {'amount': 9296}}}}},
 {'date': 1727827200,
  'circulating': {'peggedUSD': 9271},
  'bridgedTo': {'peggedUSD': 9271,
   'bridges': {'not-found': {'not-found': {'amount': 9271}}}}},
 {'date': 1727913600,
  'circulating': {'peggedUSD': 9269},
  'bridgedTo': {'peggedUSD': 9269,
   'bridges': {'not-found': {'not-found': {'amount': 9269}}}}},
 {'date': 1728000000,
  'circulating': {'peggedUSD': 9247},
  'bridgedTo': {'peggedUSD': 9247,
   'bridges': {'not-found': {'not-found': {'amount': 9247}}}}},
 {'date': 1728086400,
  'circulating': {'peggedUSD': 9208},
  'bridgedTo': {'peggedUSD': 9208,
   'bridges': {'not-found': {'not-found': {'amount': 9208}}}}},
 {'date': 1728172800,
  'circulating': {'peggedUSD': 9202},
  'bridgedTo': {'peggedUSD': 9202,
   'bridges': {'not-found': {'not-found': {'amount': 9202}}}}},
 {'date': 1728259200,
  'circulating': {'peggedUSD': 9205},
  'bridgedTo': {'peggedUSD': 9205,
   'bridges': {'not-found': {'not-found': {'amount': 9205}}}}},
 {'date': 1728345600,
  'circulating': {'peggedUSD': 9195},
  'bridgedTo': {'peggedUSD': 9195,
   'bridges': {'not-found': {'not-found': {'amount': 9195}}}}},
 {'date': 1728432000,
  'circulating': {'peggedUSD': 9133},
  'bridgedTo': {'peggedUSD': 9133,
   'bridges': {'not-found': {'not-found': {'amount': 9133}}}}},
 {'date': 1728518400,
  'circulating': {'peggedUSD': 9053},
  'bridgedTo': {'peggedUSD': 9053,
   'bridges': {'not-found': {'not-found': {'amount': 9053}}}}},
 {'date': 1728604800,
  'circulating': {'peggedUSD': 9122},
  'bridgedTo': {'peggedUSD': 9122,
   'bridges': {'not-found': {'not-found': {'amount': 9122}}}}},
 {'date': 1728691200,
  'circulating': {'peggedUSD': 9155},
  'bridgedTo': {'peggedUSD': 9155,
   'bridges': {'not-found': {'not-found': {'amount': 9155}}}}},
 {'date': 1728777600,
  'circulating': {'peggedUSD': 10393},
  'bridgedTo': {'peggedUSD': 10393,
   'bridges': {'not-found': {'not-found': {'amount': 10393}}}}},
 {'date': 1728864000,
  'circulating': {'peggedUSD': 9154},
  'bridgedTo': {'peggedUSD': 9154,
   'bridges': {'not-found': {'not-found': {'amount': 9154}}}}},
 {'date': 1728950400,
  'circulating': {'peggedUSD': 9085},
  'bridgedTo': {'peggedUSD': 9085,
   'bridges': {'not-found': {'not-found': {'amount': 9085}}}}},
 {'date': 1729036800,
  'circulating': {'peggedUSD': 9142},
  'bridgedTo': {'peggedUSD': 9142,
   'bridges': {'not-found': {'not-found': {'amount': 9142}}}}},
 {'date': 1729123200,
  'circulating': {'peggedUSD': 9217},
  'bridgedTo': {'peggedUSD': 9217,
   'bridges': {'not-found': {'not-found': {'amount': 9217}}}}},
 {'date': 1729209600,
  'circulating': {'peggedUSD': 14748},
  'bridgedTo': {'peggedUSD': 14748,
   'bridges': {'not-found': {'not-found': {'amount': 14748}}}}},
 {'date': 1729296000,
  'circulating': {'peggedUSD': 14644},
  'bridgedTo': {'peggedUSD': 14644,
   'bridges': {'not-found': {'not-found': {'amount': 14644}}}}},
 {'date': 1729382400,
  'circulating': {'peggedUSD': 9468},
  'bridgedTo': {'peggedUSD': 9468,
   'bridges': {'not-found': {'not-found': {'amount': 9468}}}}},
 {'date': 1729468800,
  'circulating': {'peggedUSD': 9256},
  'bridgedTo': {'peggedUSD': 9256,
   'bridges': {'not-found': {'not-found': {'amount': 9256}}}}},
 {'date': 1729555200,
  'circulating': {'peggedUSD': 16295},
  'bridgedTo': {'peggedUSD': 16295,
   'bridges': {'not-found': {'not-found': {'amount': 16295}}}}},
 {'date': 1729641600,
  'circulating': {'peggedUSD': 14499},
  'bridgedTo': {'peggedUSD': 14499,
   'bridges': {'not-found': {'not-found': {'amount': 14499}}}}},
 {'date': 1729728000,
  'circulating': {'peggedUSD': 14093},
  'bridgedTo': {'peggedUSD': 14093,
   'bridges': {'not-found': {'not-found': {'amount': 14093}}}}},
 {'date': 1729814400,
  'circulating': {'peggedUSD': 14339},
  'bridgedTo': {'peggedUSD': 14339,
   'bridges': {'not-found': {'not-found': {'amount': 14339}}}}},
 {'date': 1729900800,
  'circulating': {'peggedUSD': 13937},
  'bridgedTo': {'peggedUSD': 13937,
   'bridges': {'not-found': {'not-found': {'amount': 13937}}}}},
 {'date': 1729987200,
  'circulating': {'peggedUSD': 14208},
  'bridgedTo': {'peggedUSD': 14208,
   'bridges': {'not-found': {'not-found': {'amount': 14208}}}}},
 {'date': 1730073600,
  'circulating': {'peggedUSD': 14175},
  'bridgedTo': {'peggedUSD': 14175,
   'bridges': {'not-found': {'not-found': {'amount': 14175}}}}},
 {'date': 1730160000,
  'circulating': {'peggedUSD': 14456},
  'bridgedTo': {'peggedUSD': 14456,
   'bridges': {'not-found': {'not-found': {'amount': 14456}}}}},
 {'date': 1730246400,
  'circulating': {'peggedUSD': 4279504},
  'bridgedTo': {'peggedUSD': 4279504,
   'bridges': {'not-found': {'not-found': {'amount': 4279504}}}}},
 {'date': 1730332800,
  'circulating': {'peggedUSD': 4708695},
  'bridgedTo': {'peggedUSD': 4708695,
   'bridges': {'not-found': {'not-found': {'amount': 4708695}}}}},
 {'date': 1730419200,
  'circulating': {'peggedUSD': 3404228},
  'bridgedTo': {'peggedUSD': 3404228,
   'bridges': {'not-found': {'not-found': {'amount': 3404228}}}}},
 {'date': 1730505600,
  'circulating': {'peggedUSD': 2347085},
  'bridgedTo': {'peggedUSD': 2347085,
   'bridges': {'not-found': {'not-found': {'amount': 2347085}}}}},
 {'date': 1730592000,
  'circulating': {'peggedUSD': 466368},
  'bridgedTo': {'peggedUSD': 466368,
   'bridges': {'not-found': {'not-found': {'amount': 466368}}}}},
 {'date': 1730678400,
  'circulating': {'peggedUSD': 14284},
  'bridgedTo': {'peggedUSD': 14284,
   'bridges': {'not-found': {'not-found': {'amount': 14284}}}}},
 {'date': 1730764800,
  'circulating': {'peggedUSD': 15143},
  'bridgedTo': {'peggedUSD': 15143,
   'bridges': {'not-found': {'not-found': {'amount': 15143}}}}},
 {'date': 1730851200,
  'circulating': {'peggedUSD': 14240},
  'bridgedTo': {'peggedUSD': 14240,
   'bridges': {'not-found': {'not-found': {'amount': 14240}}}}},
 {'date': 1730937600,
  'circulating': {'peggedUSD': 14606403},
  'bridgedTo': {'peggedUSD': 14606403,
   'bridges': {'not-found': {'not-found': {'amount': 14606403}}}}},
 {'date': 1731024000,
  'circulating': {'peggedUSD': 18328969},
  'bridgedTo': {'peggedUSD': 18328969,
   'bridges': {'not-found': {'not-found': {'amount': 18328969}}}}},
 {'date': 1731110400,
  'circulating': {'peggedUSD': 21495565},
  'bridgedTo': {'peggedUSD': 21495565,
   'bridges': {'not-found': {'not-found': {'amount': 21495565}}}}},
 {'date': 1731196800,
  'circulating': {'peggedUSD': 20084787},
  'bridgedTo': {'peggedUSD': 20084787,
   'bridges': {'not-found': {'not-found': {'amount': 20084787}}}}},
 {'date': 1731283200,
  'circulating': {'peggedUSD': 23956174},
  'bridgedTo': {'peggedUSD': 23956174,
   'bridges': {'not-found': {'not-found': {'amount': 23956174}}}}},
 {'date': 1731369600,
  'circulating': {'peggedUSD': 34850085},
  'bridgedTo': {'peggedUSD': 34850085,
   'bridges': {'not-found': {'not-found': {'amount': 34850085}}}}},
 {'date': 1731456000,
  'circulating': {'peggedUSD': 34545181.223798},
  'minted': {'peggedUSD': 0},
  'unreleased': {'peggedUSD': 0},
  'bridgedTo': {'peggedUSD': 34545181.223798,
   'bridges': {'not-found': {'not-found': {'amount': 34545181.223798}}}}}]

In [29]:
df_eth = pl.DataFrame(df_usde['chainBalances']['Ethereum']['tokens']).with_columns(
    pl.col('circulating').struct.field('0'),
    pl.col('minted').struct.field('0')
)
df_eth

StructFieldNotFoundError: 0

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'with_columns' <---
DF ["date", "circulating", "minted"]; PROJECT */3 COLUMNS; SELECTION: None

## total supply

In [2]:
df_total_supply = stable_llama.get_total_supply()
# df_total_supply = df_total_supply.drop(['circulatingPrevWeek', 'circulatingPrevMonth'])#.sort('change_24h_pct', descending=True)

In [3]:
df_total_supply

shape: (206, 11)
┌─────┬─────────────┬────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id  ┆ name        ┆ symbol ┆ gecko_id    ┆ … ┆ circulatin ┆ circulatin ┆ change_24h ┆ change_24h │
│ --- ┆ ---         ┆ ---    ┆ ---         ┆   ┆ g          ┆ gPrevDay   ┆ ---        ┆ _pct       │
│ str ┆ str         ┆ str    ┆ str         ┆   ┆ ---        ┆ ---        ┆ f64        ┆ ---        │
│     ┆             ┆        ┆             ┆   ┆ f64        ┆ f64        ┆            ┆ f64        │
╞═════╪═════════════╪════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 1   ┆ Tether      ┆ USDT   ┆ tether      ┆ … ┆ 6.7364e10  ┆ 1.2440e11  ┆ -5.7034e10 ┆ -45.85     │
│ 2   ┆ USD Coin    ┆ USDC   ┆ usd-coin    ┆ … ┆ 3.6490e10  ┆ 3.6872e10  ┆ -3.8155e8  ┆ -1.03      │
│ 5   ┆ Dai         ┆ DAI    ┆ dai         ┆ … ┆ 4.6575e9   ┆ 4.7252e9   ┆ -6.7686e7  ┆ -1.43      │
│ 146 ┆ Ethena USDe ┆ USDe   ┆ ethena-usde ┆ … ┆ 3.0268e9   ┆ 2.9905e9   ┆ 3.6361e7   ┆ 1.22       │
│ 119 ┆ First       ┆ FDUSD  ┆ first-digit ┆ … ┆ 1.9909e9   ┆ 2.0260e9   ┆ -3.5059e7  ┆ -1.73      │
│     ┆ Digital USD ┆        ┆ al-usd      ┆   ┆            ┆            ┆            ┆            │
│ …   ┆ …           ┆ …      ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 182 ┆ Zunami ETH  ┆ zunETH ┆ zunETH      ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ 183 ┆ Bitcoin USD ┆ BtcUSD ┆ bitcoin-usd ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆             ┆        ┆ -btcfi      ┆   ┆            ┆            ┆            ┆            │
│ 186 ┆ Internation ┆ ISC    ┆ internation ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆ al Stable   ┆        ┆ al-stable-c ┆   ┆            ┆            ┆            ┆            │
│     ┆ Currency    ┆        ┆ urrency     ┆   ┆            ┆            ┆            ┆            │
│ 199 ┆ Celo Real   ┆ CREAL  ┆ celo-real-c ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆             ┆        ┆ real        ┆   ┆            ┆            ┆            ┆            │
│ 200 ┆ Hedera      ┆ HCHF   ┆ hedera-swis ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆ Swiss Franc ┆        ┆ s-franc     ┆   ┆            ┆            ┆            ┆            │
└─────┴─────────────┴────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [4]:
df_total_supply['pegMechanism'].value_counts()

shape: (3, 2)
┌───────────────┬───────┐
│ pegMechanism  ┆ count │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ crypto-backed ┆ 127   │
│ algorithmic   ┆ 27    │
│ fiat-backed   ┆ 52    │
└───────────────┴───────┘

In [5]:
df_total_supply.filter(
    (pl.col('symbol') == 'USDe')
    # & (pl.col('circulating') > 1e6)
    # & (pl.col('pegMechanism') != "fiat-backed")
)

shape: (1, 11)
┌─────┬────────┬────────┬──────────────┬───┬──────────────┬─────────────┬────────────┬─────────────┐
│ id  ┆ name   ┆ symbol ┆ gecko_id     ┆ … ┆ circulating  ┆ circulating ┆ change_24h ┆ change_24h_ │
│ --- ┆ ---    ┆ ---    ┆ ---          ┆   ┆ ---          ┆ PrevDay     ┆ ---        ┆ pct         │
│ str ┆ str    ┆ str    ┆ str          ┆   ┆ f64          ┆ ---         ┆ f64        ┆ ---         │
│     ┆        ┆        ┆              ┆   ┆              ┆ f64         ┆            ┆ f64         │
╞═════╪════════╪════════╪══════════════╪═══╪══════════════╪═════════════╪════════════╪═════════════╡
│ 146 ┆ Ethena ┆ USDe   ┆ ethena-usde  ┆ … ┆ 3.0268e9     ┆ 2.9905e9    ┆ 3.6361e7   ┆ 1.22        │
│     ┆ USDe   ┆        ┆              ┆   ┆              ┆             ┆            ┆             │
└─────┴────────┴────────┴──────────────┴───┴──────────────┴─────────────┴────────────┴─────────────┘

In [6]:
df_chains = stable_llama.get_chain_circulation()

Error processing Reservoir Stablecoin on Ethereum: 'int' object has no attribute 'values'

In [31]:
df_chains_filtered = df_chains.filter(
    pl.col('coin').is_in(ll)
    & (pl.col('change_24h') != 0.0)
)#.sort('change_24h_pct', descending=True)

In [34]:
df_chains_filtered#.group_by('coin').agg(pl.col('change_24h').sum())

shape: (5, 8)
┌────────────┬────────┬──────────┬─────────────┬─────────────┬──────────┬─────────────┬────────────┐
│ coin       ┆ symbol ┆ chain    ┆ current     ┆ prev_day    ┆ price    ┆ change_24h  ┆ change_24h │
│ ---        ┆ ---    ┆ ---      ┆ ---         ┆ ---         ┆ ---      ┆ ---         ┆ _pct       │
│ str        ┆ str    ┆ str      ┆ f64         ┆ f64         ┆ f64      ┆ f64         ┆ ---        │
│            ┆        ┆          ┆             ┆             ┆          ┆             ┆ f64        │
╞════════════╪════════╪══════════╪═════════════╪═════════════╪══════════╪═════════════╪════════════╡
│ sUSD       ┆ SUSD   ┆ Optimism ┆ 1.9726e7    ┆ 2.2301e7    ┆ 1.001    ┆ -2.5743e6   ┆ -11.54     │
│ sUSD       ┆ SUSD   ┆ Ethereum ┆ 1.0912e7    ┆ 1.1484e7    ┆ 1.001    ┆ -572031.655 ┆ -4.98      │
│            ┆        ┆          ┆             ┆             ┆          ┆ 245         ┆            │
│ USDT+      ┆ USDT+  ┆ Arbitrum ┆ 2.9380e6    ┆ 3.1115e6    ┆ 0.997656 ┆ -173474.296 ┆ -5.58      │
│            ┆        ┆          ┆             ┆             ┆          ┆ 28          ┆            │
│ USDT+      ┆ USDT+  ┆ Linea    ┆ 18368.46473 ┆ 18385.18690 ┆ 0.997656 ┆ -16.722172  ┆ -0.09      │
│            ┆        ┆          ┆ 7           ┆ 9           ┆          ┆             ┆            │
│ Zunami USD ┆ zunUSD ┆ Ethereum ┆ 1.9436e6    ┆ 2.1640e6    ┆ 0.992873 ┆ -220325.868 ┆ -10.18     │
│            ┆        ┆          ┆             ┆             ┆          ┆ 24          ┆            │
└────────────┴────────┴──────────┴─────────────┴─────────────┴──────────┴─────────────┴────────────┘

In [35]:
df_total_supply.filter(
    pl.col('name').is_in(ll)
    # & (pl.col('change_24h') != 0.0)
)#.sort('change_24h_pct', descending=True)

shape: (3, 11)
┌─────┬────────────┬────────┬──────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ id  ┆ name       ┆ symbol ┆ gecko_id ┆ … ┆ circulating ┆ circulating ┆ change_24h  ┆ change_24h_ │
│ --- ┆ ---        ┆ ---    ┆ ---      ┆   ┆ ---         ┆ PrevDay     ┆ ---         ┆ pct         │
│ str ┆ str        ┆ str    ┆ str      ┆   ┆ f64         ┆ ---         ┆ f64         ┆ ---         │
│     ┆            ┆        ┆          ┆   ┆             ┆ f64         ┆             ┆ f64         │
╞═════╪════════════╪════════╪══════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 22  ┆ sUSD       ┆ SUSD   ┆ nusd     ┆ … ┆ 3.0639e7    ┆ 3.3785e7    ┆ -3.1463e6   ┆ -9.31       │
│ 112 ┆ USDT+      ┆ USDT+  ┆ usdtplus ┆ … ┆ 2.9851e6    ┆ 3.1586e6    ┆ -173491.018 ┆ -5.49       │
│     ┆            ┆        ┆          ┆   ┆             ┆             ┆ 452         ┆             │
│ 181 ┆ Zunami USD ┆ zunUSD ┆ zunUSD   ┆ … ┆ 1.9436e6    ┆ 2.1640e6    ┆ -220325.868 ┆ -10.18      │
│     ┆            ┆        ┆          ┆   ┆             ┆             ┆ 24          ┆             │
└─────┴────────────┴────────┴──────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [ ]:
name = 'sUSD'
chain = "Optimism"
contract_address = "0x8c6f28f2f1a3c87f0f938b96d27520d9751ec8d9"
"""
Transfer
43422
Approval
8446
Issued
2125
Burned
444
"""

In [59]:
# Read first 5 lines as column names
with open('c.txt', 'r') as f:
    columns = [next(f).strip() for _ in range(5)]

# Read remaining lines in groups of 5 as data rows
data = []
with open('c.txt', 'r') as f:
    # Skip the column headers
    for _ in range(5):
        next(f)
        
    # Read data rows
    while True:
        try:
            row = [next(f).strip() for _ in range(5)]
            data.append(row)
        except StopIteration:
            break

# Create DataFrame
df_transfers = pl.DataFrame(
    data,
    schema=columns
)
df_transfers = df_transfers.with_columns(
    pl.col('total_amount').cast(pl.Float64)
)
df_transfers

shape: (75, 5)
┌────────────────────┬────────────────────┬────────────────────┬───────────────────┬───────────────┐
│ transfer_from      ┆ transfer_to        ┆ tx_from            ┆ tx_to             ┆ total_amount  │
│ ---                ┆ ---                ┆ ---                ┆ ---               ┆ ---           │
│ str                ┆ str                ┆ str                ┆ str               ┆ f64           │
╞════════════════════╪════════════════════╪════════════════════╪═══════════════════╪═══════════════╡
│ 0xe2101d19b78e6959 ┆ 0xbce24f7e2bfd63e5 ┆ 0x2e8d0cc9ab070d13 ┆ 0xb8b2ec7346c3989 ┆ 2.9247e7      │
│ 82975cc1a27b…      ┆ 90bf18524e80…      ┆ 36188c907b56…      ┆ e13cf03f22885…    ┆               │
│ 0xbce24f7e2bfd63e5 ┆ 0xe2101d19b78e6959 ┆ 0x2e8d0cc9ab070d13 ┆ 0xb8b2ec7346c3989 ┆ 2.8285e7      │
│ 90bf18524e80…      ┆ 82975cc1a27b…      ┆ 36188c907b56…      ┆ e13cf03f22885…    ┆               │
│ 0xcc7d6ed524760539 ┆ 0x0000000000000000 ┆ 0xc8c3ba0fc3f934a7 ┆ 0xcc7d6ed52476053 ┆ 1.3956e6      │
│ 311ed0cdb41d…      ┆ 000000000000…      ┆ 66ba51efc742…      ┆ 9311ed0cdb41d…    ┆               │
│ 0x7d3c9c6566375d7a ┆ 0x0000000000000000 ┆ 0x7ce3c65e832ca68c ┆ 0x7d3c9c6566375d7 ┆ 1.2288e6      │
│ d6e89169ca5c…      ┆ 000000000000…      ┆ 8f364ce294e8…      ┆ ad6e89169ca5c…    ┆               │
│ 0xe2101d19b78e6959 ┆ 0xbce24f7e2bfd63e5 ┆ 0xc2d9f9840bfc6a0f ┆ 0xe82343a116d2179 ┆ 1.0939e6      │
│ 82975cc1a27b…      ┆ 90bf18524e80…      ┆ 48f5dfef6868…      ┆ f197111d92f9b…    ┆               │
│ …                  ┆ …                  ┆ …                  ┆ …                 ┆ …             │
│ 0xd712e1bf0090691c ┆ 0x6d80113e533a2c0f ┆ 0xd712e1bf0090691c ┆ 0x794a61358d68455 ┆ 165567.424016 │
│ fba1f74ce2d9…      ┆ e82eabd35f18…      ┆ fba1f74ce2d9…      ┆ 94f94dc1db02a…    ┆               │
│ 0x88b3dc3dcd06f148 ┆ 0x0000000000000000 ┆ 0x11e82bbd9477f625 ┆ 0x88b3dc3dcd06f14 ┆ 159320.0      │
│ 9d1879f4e465…      ┆ 000000000000…      ┆ 62c88b140d2d…      ┆ 89d1879f4e465…    ┆               │
│ 0x3bdd90f6b6c6eb35 ┆ 0x0000000000000000 ┆ 0x0514f2f3e0277c47 ┆ 0x3bdd90f6b6c6eb3 ┆ 158000.0      │
│ 0c09d0dfe55a…      ┆ 000000000000…      ┆ 117e3f33d939…      ┆ 50c09d0dfe55a…    ┆               │
│ 0x0000000000000000 ┆ 0x25b6f5f1525f0074 ┆ 0x36bde71c97b33cc4 ┆ 0x420000000000000 ┆ 154538.696532 │
│ 000000000000…      ┆ d53570ea2fb4…      ┆ 729cf772ae26…      ┆ 0000000000000…    ┆               │
│ 0x4f754e0f0924afd7 ┆ 0x2ed1bd7f66e47113 ┆ 0x47ed85091b17ce35 ┆ 0x2ed1bd7f66e4711 ┆ 154148.832572 │
│ 4980886b0b47…      ┆ 672f3870308b…      ┆ c39563c25dcb…      ┆ 3672f3870308b…    ┆               │
└────────────────────┴────────────────────┴────────────────────┴───────────────────┴───────────────┘

In [65]:
labels = {
    '0xe2101d19b78e695982975cc1a27b6a9117e02b09': 'UniswapV3Pool',
    '0xbce24f7e2bfd63e590bf18524e80b222f7c982d8': 'beefy_BeaconProxy',
    '0x2e8d0cc9ab070d1336188c907b565565f9c03bb5': 'chad_1',
    '0xb8b2ec7346c3989e13cf03f228851237cd9a9c26': 'chad_contract',
    '0xcc7d6ed524760539311ed0cdb41d0852b4eb77eb': 'solana_bull_3x',
    '0x7d3c9c6566375d7ad6e89169ca5c01b5edc15364': 'solana_bull_2x',
    '0xc8c3ba0fc3f934a766ba51efc742ca359dae82bd': 'chad_2',
    '0xe82343a116d2179f197111d92f9b53611b43c01c': 'BeefyZapRouter',
    '0xfb73dbc7ead4671edac2f471ad50e205cf352c68': 'chad_3',
    '0x7ce3c65e832ca68c8f364ce294e80b603376acff': 'chad_4',
    '0x0000000000000000000000000000000000000000': 'zero_address',
    '0xbc5a22f6df95f987ceef999cc812ed272a9b938a': 'chad_5',
    '0xc2d9f9840bfc6a0f48f5dfef686878534fca5b22': 'chad_6',


}

In [66]:

df_transfers.with_columns(
    pl.col('transfer_from').replace(labels).alias('transfer_from'),
    pl.col('transfer_to').replace(labels).alias('transfer_to'),
    pl.col('tx_from').replace(labels).alias('tx_from'),
    pl.col('tx_to').replace(labels).alias('tx_to')

).head(10)
# 2024-10-28 22:31:04, last 24h

shape: (10, 5)
┌───────────────────┬───────────────────┬─────────────────────┬────────────────────┬───────────────┐
│ transfer_from     ┆ transfer_to       ┆ tx_from             ┆ tx_to              ┆ total_amount  │
│ ---               ┆ ---               ┆ ---                 ┆ ---                ┆ ---           │
│ str               ┆ str               ┆ str                 ┆ str                ┆ f64           │
╞═══════════════════╪═══════════════════╪═════════════════════╪════════════════════╪═══════════════╡
│ UniswapV3Pool     ┆ beefy_BeaconProxy ┆ chad_1              ┆ chad_contract      ┆ 2.9247e7      │
│ beefy_BeaconProxy ┆ UniswapV3Pool     ┆ chad_1              ┆ chad_contract      ┆ 2.8285e7      │
│ solana_bull_3x    ┆ zero_address      ┆ chad_2              ┆ solana_bull_3x     ┆ 1.3956e6      │
│ solana_bull_2x    ┆ zero_address      ┆ chad_4              ┆ solana_bull_2x     ┆ 1.2288e6      │
│ UniswapV3Pool     ┆ beefy_BeaconProxy ┆ chad_6              ┆ BeefyZapRouter     ┆ 1.0939e6      │
│ beefy_BeaconProxy ┆ UniswapV3Pool     ┆ chad_6              ┆ BeefyZapRouter     ┆ 1.0911e6      │
│ UniswapV3Pool     ┆ beefy_BeaconProxy ┆ 0x59e7b9be88b69ec43 ┆ BeefyZapRouter     ┆ 1.0833e6      │
│                   ┆                   ┆ dc0ae9da93a…        ┆                    ┆               │
│ beefy_BeaconProxy ┆ UniswapV3Pool     ┆ 0x59e7b9be88b69ec43 ┆ BeefyZapRouter     ┆ 1.0751e6      │
│                   ┆                   ┆ dc0ae9da93a…        ┆                    ┆               │
│ beefy_BeaconProxy ┆ UniswapV3Pool     ┆ 0x417b4adc279743fc4 ┆ 0x01051113d81d7d6d ┆ 1.0485e6      │
│                   ┆                   ┆ 9f047c323fc…        ┆ a508462f2ad6…      ┆               │
│ beefy_BeaconProxy ┆ UniswapV3Pool     ┆ 0x15eeb6dcdf2ef7287 ┆ BeefyZapRouter     ┆ 896490.008303 │
│                   ┆                   ┆ eb4e534331a…        ┆                    ┆               │
└───────────────────┴───────────────────┴─────────────────────┴────────────────────┴───────────────┘